server:
  port: 8081

spring:
  application:
    name: product-catalog
  datasource:
    url: jdbc:h2:mem:inventorydb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

app:
  kafka:
    enabled: false
    topics:
      style-created: style.created.v1
      product-created: product.created.v1
      ticket-price-updated: ticket-price.updated.v1
      order-placed: order.placed.v1
      inventory-updated: inventory.updated.v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sai@143
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: kafka-inmemory
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}

app:
  kafka:
    enabled: true
